const QUESTOES = [
['Qual modelo é apresentado como adequado para aplicações Web por ser flexível e permitir mudanças entre versões?',['Cascata','Incremental','Prototipagem','RAD','Espiral'],1,'O material apresenta o Modelo Incremental como adequado por sua flexibilidade, testes e mudanças entre versões.'],
['Qual é a função de um banco de dados?',['Apenas exibir páginas','Armazenar informações que podem ser consultadas e alteradas','Criar diagramas UML','Executar CSS','Substituir o servidor'],1,'O banco de dados armazena informações que podem ser lidas e alteradas.'],
['O que é o modelo lógico?',['Modelo de ações do usuário','Mapa dos dados da solução escolhida para a aplicação','Lista de linguagens usadas','Modelo visual da página','Sistema de autenticação'],1,'O material define o modelo lógico como o mapeamento dos dados da solução escolhida.'],
['Qual é a função da chave primária?',['Relacionar duas páginas','Identificar registros em uma tabela','Executar PHP','Armazenar imagens','Excluir tabelas'],1,'A chave primária é usada como identificador/índice do registro.'],
['O que é uma chave estrangeira?',['Uma senha do banco','Uma coluna que relaciona uma tabela com a chave de outra tabela','Um comando PHP','Um tipo de sessão','Um verbo HTTP'],1,'Ela faz a relação entre tabelas usando a chave de outra tabela.'],
['Qual é a função do Diagrama de Casos de Uso?',['Definir a linguagem de programação','Descrever requisitos funcionais de forma simples','Criar tabelas SQL','Definir cores da interface','Controlar sessões'],1,'O material destaca a descrição simples dos requisitos funcionais.'],
['O que os atores representam em um Diagrama de Casos de Uso?',['Apenas programadores','Papéis e funções dos participantes no contexto do sistema','Tabelas do banco','Servidores','Arquivos PHP'],1,'Atores representam papéis e funções dentro do contexto do sistema.'],
['Quais são os três tipos de relacionamentos citados no material?',['Usuário, servidor e banco','Ator-caso de uso, atores e casos de uso','HTML, CSS e JS','GET, POST e PUT','Classe, método e atributo'],1,'São relações entre ator e caso de uso, entre atores e entre casos de uso.'],
['Qual é a função do DER?',['Definir a cor do site','Modelar conceitos que devem ser armazenados no banco','Executar consultas','Criar sessões','Definir a linguagem PHP'],1,'O DER representa a modelagem dos conceitos armazenados no banco.'],
['Qual alternativa descreve melhor o PHP no material?',['Roda apenas no navegador','Processa no servidor e retorna o resultado ao cliente','É somente banco de dados','É um protocolo XML','É um editor visual'],1,'O PHP é apresentado como linguagem de script com processamento no lado do servidor.'],
['Como uma variável PHP é declarada?',['#nome','@nome','$nome','%nome','nome$'],2,'O PHP usa $ antes do nome da variável.'],
['O PHP resolve os tipos de dados de forma:',['Sempre manual','Dinamicamente','Somente pelo HTML','Apenas pelo MySQL','Somente pelo CSS'],1,'O material destaca que não é obrigatório informar o tipo na declaração.'],
['Qual alternativa contém operadores de atribuição citados no material?',['==, ===, !=','=, +=, /=, .=','<, >, <=','&&, ||, !','++, --, **'],1,'O gabarito do material aponta =, +=, /= e .=.'],
['Para que serve o for?',['Repetir código por um número conhecido de vezes','Criar uma tabela','Iniciar sessão','Conectar ao MySQL','Criar um WSDL'],0,'O for é usado para repetir determinado código em um número de vezes conhecido.'],
['Qual superglobal é usada no material para receber dados enviados por POST?',['$_GET','$_SESSION','$_POST','$_SERVER','$_COOKIE'],2,'Formulários enviados por POST podem ser recebidos com $_POST.'],
['O que é uma função em PHP?',['Um banco de dados','Um bloco de instruções que pode ser chamado quando necessário','Uma tabela','Uma página HTML','Um ator UML'],1,'Função é um bloco de instruções que realiza um procedimento e pode ser chamado.'],
['Uma vantagem da programação orientada a objetos destacada no material é:',['Aumentar repetições','Reduzir redundâncias e repetições','Eliminar banco de dados','Substituir HTML','Impedir classes'],1,'O material destaca redução de redundâncias e repetições.'],
['O que é uma classe?',['Uma estrutura que define dados, atributos e métodos dos objetos','Uma variável de sessão','Um verbo HTTP','Uma tabela obrigatoriamente','Um formulário'],0,'Classe é a estrutura que define tipos de dados, atributos e métodos dos objetos.'],
['Para que serve uma sessão?',['Manter informações entre páginas do site','Criar CSS','Excluir tabelas','Gerar XML','Definir atores'],0,'Sessão mantém informações salvas entre páginas.'],
['Qual comando inicia uma sessão PHP?',['session_destroy()','session_start()','mysqli_num_rows()','require_once()','start_session()'],1,'session_start() inicia a sessão.'],
['Qual comando encerra uma sessão PHP?',['session_start()','session_close()','session_destroy()','unset_session()','end()'],2,'session_destroy() é o comando indicado no material para encerrar a sessão.'],
['Quais extensões são citadas para trabalhar com MySQL em PHP?',['MySQL, MySQLi e PDO','HTML, CSS e JS','SOAP, REST e XML','GET, POST e PUT','UML, DER e WSDL'],0,'O material cita MySQL, MySQLi e PDO.'],
['Quais comandos podem ser usados para reutilizar outros scripts?',['include, include_once, require e require_once','SELECT, UPDATE e DELETE','GET, POST e PUT','class, function e echo','start, stop e close'],0,'Esses quatro comandos são citados no material.'],
['Qual função retorna o número de linhas de um resultado MySQLi?',['mysqli_rows()','mysqli_num_rows()','mysql_count()','num_rows()','count_mysql()'],1,'O material aponta mysqli_num_rows.'],
['Qual exemplo representa uma conexão MySQLi orientada a objetos?',['$conn = mysql();','$conn = new mysqli(servidor, usuario, senha, banco_de_dados);','$db = SELECT * FROM banco;','$conn = new PDO(servidor);','$mysqli = connect();'],1,'Esse é o padrão de conexão apresentado no material.'],
['Qual comando é usado como consulta simples no material?',['UPDATE banco SET x=1','SELECT * FROM banco','INSERT banco','GET /banco','CREATE PHP'],1,'O exemplo apresentado é $sql = "SELECT * FROM banco".'],
['No desafio de atualização de produto, qual comando SQL grava os dados alterados?',['SELECT','UPDATE','GET','INSERT apenas','DROP'],1,'O desafio usa UPDATE para gravar nome/valor alterados.'],
['SOAP é apresentado como um protocolo baseado em:',['JSON','XML','CSS','SQL','HTML'],1,'O material define SOAP como baseado em XML.'],
['O que pode melhorar a eficiência do SOAP segundo o material?',['Adicionar mais cabeçalhos','Reduzir ou eliminar elementos de cabeçalho','Eliminar mensagens','Trocar XML por CSS','Usar apenas GET'],1,'A redução/eliminação de elementos de cabeçalho é a resposta indicada.'],
['Qual recurso o material associa ao SOAP?',['RPC','DOM','CSS Grid','MVC','CRUD'],0,'O material apresenta chamadas de procedimentos remotos (RPC) como recurso do SOAP.'],
['Qual verbo HTTP é associado à criação de um novo registro em REST?',['GET','POST','PUT','DELETE','PATCH'],1,'No material: GET recuperação, POST criação, PUT atualização/substituição e DELETE exclusão.']
].map((q,i)=>({n:i+1,enunciado:q[0],opcoes:q[1],correta:q[2],explicacao:q[3]}));
const DESAFIOS=[
['Desafio 1 — Modelos de desenvolvimento','Por que o material considera o Modelo Incremental adequado para aplicações Web?','Resposta esperada: porque é flexível, permite testes com o usuário, facilita mudanças entre versões e melhora o gerenciamento de riscos.'],
['Desafio 2 — Modelo lógico','Imagine um sistema de loja com Usuários, Produtos e Pagamento. Como essas tabelas podem se relacionar?','Resposta esperada: o modelo lógico terá as três tabelas, e Pagamento pode fazer a ligação com Usuários e Produtos por meio de chaves estrangeiras.'],
['Desafio 3 — PHP e formulário','Um formulário envia nome e ano de nascimento. O que o PHP precisa fazer?','Resposta esperada: receber os dados com $_POST, obter o ano atual com date("Y"), calcular a idade e mostrar se a pessoa é maior ou menor de idade.'],
['Desafio 4 — Sessão','Como salvar nome e e-mail em uma sessão e permitir que o usuário saia?','Resposta esperada: usar session_start(), salvar os dados em $_SESSION, mostrar uma mensagem personalizada e usar session_destroy() para encerrar. O padrão do professor também utiliza unset() para remover os dados.'],
['Desafio 5 — MySQL','Como funciona o fluxo básico de alteração de um produto no padrão mostrado pelo professor?','Resposta esperada: Altera.php faz um SELECT e monta o formulário; Grava.php recebe os dados e executa um UPDATE, verificando se a operação deu certo.'],
['Desafio 6 — SOAP','O que precisa ser alterado ao adicionar uma função a um serviço SOAP?','Resposta esperada: alterar a implementação do serviço, atualizar o WSDL e mensagens de entrada/saída; o WSDL publicado e os clientes consumidores também podem precisar ser atualizados/regenerados.']
];
const FLASH=[
['Modelo Incremental','Modelo apresentado como flexível e adequado para mudanças entre versões.'],['Banco de dados','Armazena informações que podem ser consultadas e alteradas.'],['Modelo lógico','Mapeia os dados da solução escolhida para a aplicação.'],['Chave primária','Identifica registros em uma tabela.'],['Chave estrangeira','Relaciona tabelas por meio de uma chave de outra tabela.'],['Casos de Uso','Descreve requisitos funcionais de forma simples.'],['Ator','Representa um papel/função no contexto do sistema.'],['DER','Modela conceitos que devem ser armazenados no banco.'],['PHP','Linguagem de script com processamento no servidor.'],['Variável PHP','$ antes do nome, como $nome.'],['$_POST','Recebe dados enviados por POST.'],['for','Repete código por um número conhecido de vezes.'],['Função','Bloco de instruções chamado quando necessário.'],['Classe','Define dados, atributos e métodos dos objetos.'],['Sessão','Mantém informações entre páginas.'],['session_start()','Inicia uma sessão PHP.'],['session_destroy()','Encerra uma sessão PHP.'],['MySQLi','Extensão/interface para trabalhar com MySQL.'],['mysqli_num_rows()','Obtém o número de linhas de um resultado.'],['SELECT','Consulta dados.'],['UPDATE','Atualiza dados existentes.'],['SOAP','Protocolo baseado em XML para troca de dados entre aplicações.'],['REST','Arquitetura apresentada como alternativa mais leve ao SOAP e stateless.'],['POST','Verbo HTTP usado para criação de registro no material.']
];
const nav=document.querySelectorAll('.nav-btn'),views=document.querySelectorAll('.view'),hero=document.querySelector('.hero');
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));nav.forEach(b=>b.classList.toggle('active',b.dataset.target===id));hero.style.display=id==='resumo'?'':'none';scrollTo({top:0,behavior:'smooth'})}
nav.forEach(b=>b.onclick=()=>showView(b.dataset.target));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>showView(b.dataset.jump));
const quiz=document.getElementById('quiz'),letters=['A','B','C','D','E'];
QUESTOES.forEach(q=>{const d=document.createElement('div');d.className='question';d.innerHTML=`<div class="question-head"><span class="q-num">${q.n}</span><span class="q-text">${q.enunciado}</span></div><div class="options">${q.opcoes.map((o,i)=>`<label class="option"><input type="radio" name="q${q.n}" value="${i}"><span><strong>${letters[i]})</strong> ${o}</span></label>`).join('')}</div><div class="explain"><strong>Por quê:</strong> ${q.explicacao}</div>`;quiz.appendChild(d)});
function progress(){let n=QUESTOES.filter(q=>document.querySelector(`input[name=q${q.n}]:checked`)).length;document.getElementById('progressBar').style.width=(n/QUESTOES.length*100)+'%';document.getElementById('progressText').textContent=`${n} / ${QUESTOES.length} respondidas`}
quiz.addEventListener('change',e=>{if(e.target.type!=='radio')return;e.target.closest('.options').querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));e.target.closest('.option').classList.add('selected');progress()});
document.getElementById('btnCorrigir').onclick=()=>{let ac=0;document.querySelectorAll('.question').forEach((d,i)=>{let q=QUESTOES[i],sel=d.querySelector('input:checked'),opts=d.querySelectorAll('.option');opts[q.correta].classList.add('correct');if(sel){let v=+sel.value;if(v===q.correta)ac++;else opts[v].classList.add('wrong')}d.querySelector('.explain').classList.add('show')});let pct=Math.round(ac/QUESTOES.length*100),c=pct>=90?'good':pct>=70?'mid':'bad',msg=pct>=90?'Mandou muito bem! 🎉':pct>=70?'Boa! Revise os erros. 👀':'Vale revisar os módulos e tentar novamente. 💪';document.getElementById('resultado').innerHTML=`<h3>Resultado</h3><div class="score ${c}">${ac}/${QUESTOES.length}</div><p><strong>${pct}% de acerto.</strong> ${msg}</p>`;document.getElementById('resultado').hidden=false;document.getElementById('resultado').scrollIntoView({behavior:'smooth',block:'center'})};
document.getElementById('btnRefazer').onclick=()=>{document.querySelectorAll('input[type=radio]').forEach(x=>x.checked=false);document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected','correct','wrong'));document.querySelectorAll('.explain').forEach(x=>x.classList.remove('show'));document.getElementById('resultado').hidden=true;progress();scrollTo({top:0,behavior:'smooth'})};
const prova=document.getElementById('provaLista');DESAFIOS.forEach((p,i)=>{let d=document.createElement('div');d.className='prova-item';d.innerHTML=`<div class="prova-head"><span class="prova-num">${i+1}</span><span class="prova-pergunta">${p[0]}<br>${p[1]}</span></div><div class="prova-dica">Tente explicar sem olhar o material.</div><button class="prova-btn">👁️ Ver resposta</button><div class="prova-resposta">${p[2]}</div>`;let b=d.querySelector('.prova-btn'),r=d.querySelector('.prova-resposta');b.onclick=()=>{let open=r.classList.toggle('show');b.textContent=open?'🙈 Esconder resposta':'👁️ Ver resposta'};prova.appendChild(d)});
const cards=document.getElementById('cards');FLASH.forEach(x=>{let c=document.createElement('div');c.className='flashcard';c.innerHTML=`<div class="flashcard-inner"><div class="flashcard-face flashcard-front"><span>${x[0]}</span><small>clique para virar →</small></div><div class="flashcard-face flashcard-back"><div><strong>${x[0]}</strong>${x[1]}</div></div></div>`;c.onclick=()=>c.classList.toggle('flipped');cards.appendChild(c)});
